version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_BASE_URL: ${OPENAI_API_BASE_URL}
      OPENAI_API_MODEL: ${OPENAI_API_MODEL}
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}
      TIMEOUT_MS: ${TIMEOUT_MS}
  nginx:
    image: nginx:alpine
    ports:
      - '3002:80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
